#  _                       _          _________  ___
# | |                     | |         | ___ \  \/  |
# | |     ___   __ _  __ _| | ___ _ __| |_/ / .  . |
# | |    / _ \ / _` |/ _` | |/ _ \ '__|  __/| |\/| |
# | |___| (_) | (_| | (_| | |  __/ |  | |   | |  | |
# \_____/\___/ \__, |\__, |_|\___|_|  \_|   \_|  |_/
#               __/ | __/ |
#              |___/ |___/
#
# {file-description}

# {version-description1}
# {version-description2}
version: 1.0.0

# {language-description1}
# {language-description2}
# {language-description3}
language: {language}

# {cleanup-description1}
# {cleanup-description2}
# {cleanup-description3}
# {cleanup-description4}
cleanup: {cleanup}