#  _                       _          _________  ___
# | |                     | |         | ___ \  \/  |
# | |     ___   __ _  __ _| | ___ _ __| |_/ / .  . |
# | |    / _ \ / _` |/ _` | |/ _ \ '__|  __/| |\/| |
# | |___| (_) | (_| | (_| | |  __/ |  | |   | |  | |
# \_____/\___/ \__, |\__, |_|\___|_|  \_|   \_|  |_/
#               __/ | __/ |
#              |___/ |___/
#
# ----- LoggerPM Configuration File (設定ファイル) -----

# Language (言語)
language: eng